import type { ConceptEntry } from "@/components/technical-analysis/ConceptAccordion";

const GEO = "var(--cat-8)";
const COMMODITY = "var(--gold)";

export const politicalConcepts: ConceptEntry[] = [
  {
    id: "elections",
    term: "Elections",
    def: "A change (or expected change) in government leadership, which can shift fiscal policy, trade relationships, and regulatory direction.",
    accent: GEO,
    how: "Markets price in the expected policy path of the likely winner well before election day, then reprice sharply if the actual result surprises that expectation.",
    bullish: "A market-friendly, pro-growth candidate wins as expected (or unexpectedly) — the currency can rally on reduced policy uncertainty.",
    bearish: "A surprise result seen as less market-friendly, or a contested/unclear outcome, tends to weigh on the currency through added uncertainty.",
    mistake: "Assuming polls guarantee the outcome — surprise election results are exactly the kind of event that causes the sharpest currency gaps.",
    tip: "Uncertainty itself is often more damaging to a currency than either outcome — expect volatility to fall once the result (any result) is confirmed.",
  },
  {
    id: "political-instability",
    term: "Political Instability",
    def: "Domestic turmoil — leadership crises, coalition collapses, mass protests — that raises doubt about a government's ability to govern effectively.",
    accent: GEO,
    how: "Investors dislike uncertainty above almost everything else; instability makes it harder to predict fiscal policy, so capital often looks for the exit.",
    bullish: "Instability resolving (a new stable government forms, a crisis ends) tends to support a currency as uncertainty eases.",
    bearish: "Escalating instability tends to pressure a currency as investors discount the risk of policy paralysis or capital controls.",
    mistake: "Assuming political noise always translates into currency moves — markets can shrug off instability that doesn't threaten actual policy or debt stability.",
    tip: "Watch government bond yields alongside the currency — a sharp yield spike often confirms the market is genuinely worried, not just reacting to headlines.",
  },
  {
    id: "government-policies",
    term: "Government Policies",
    def: "Fiscal decisions made by elected governments (not central banks) — taxation, spending, subsidies, and regulation.",
    accent: GEO,
    how: "Large spending or tax changes affect growth, debt levels, and inflation, all of which eventually feed into how a central bank and the market view the currency.",
    bullish: "Credible fiscal discipline (controlled spending, falling debt-to-GDP) tends to support long-term currency confidence.",
    bearish: "Large, unfunded spending increases or tax cuts can raise concerns about debt sustainability and pressure the currency.",
    mistake: "Separating fiscal policy from monetary policy entirely — the two interact constantly, and large fiscal moves can force a central bank's hand.",
    tip: "Budget announcements and fiscal updates are scheduled, calendar-worthy events in their own right — treat them like any other high-impact release.",
  },
  {
    id: "trade-wars",
    term: "Trade Wars",
    def: "Escalating tariffs and trade restrictions between countries, usually in retaliation for each other's policies.",
    accent: GEO,
    how: "Tariffs raise costs for businesses and consumers, disrupt supply chains, and threaten export-dependent sectors — all of which weigh on growth expectations.",
    bullish: "A country less exposed to the specific trade dispute can see its currency relatively strengthen versus the countries directly involved.",
    bearish: "Currencies of export-heavy economies directly targeted by new tariffs tend to weaken as growth expectations for that economy fall.",
    mistake: "Assuming trade war impact is evenly spread — some currencies (and sectors) are far more exposed than others to any given dispute.",
    tip: "Watch currencies with heavy trade exposure to the countries involved — even those not directly targeted can move on spillover risk.",
  },
  {
    id: "sanctions",
    term: "Sanctions",
    def: "Economic penalties imposed by one country (or bloc) on another — restricting trade, freezing assets, or cutting access to financial systems.",
    accent: GEO,
    how: "Sanctions directly restrict capital flows and trade with the targeted country, often causing a sharp, immediate currency reaction as normal flows are disrupted.",
    bullish: "Sanctions being eased or lifted can trigger a sharp relief rally in the affected currency as normal flows resume.",
    bearish: "New or expanded sanctions typically cause an immediate, sharp decline in the targeted country's currency.",
    mistake: "Underestimating how illiquid a sanctioned currency's market can become — normal price action assumptions may not hold.",
    tip: "Sanctions news tends to move fast and gap markets — this is a case where headline risk genuinely outweighs technical levels.",
  },
  {
    id: "geopolitical-conflicts",
    term: "Geopolitical Conflicts",
    def: "Wars, military escalations, and international disputes that create broad uncertainty across global markets.",
    accent: GEO,
    how: "Conflict disrupts trade routes, energy supply, and investor confidence broadly — the reaction often extends well beyond the currencies of the countries directly involved.",
    bullish: "Safe-haven currencies (USD, JPY, CHF) and safe-haven commodities (gold) often strengthen as capital flees to perceived safety.",
    bearish: "Currencies of countries near the conflict, or heavily dependent on affected trade/energy routes, often weaken sharply.",
    mistake: "Trading the first headline reaction without confirming details — early conflict headlines are often incomplete or later revised.",
    tip: "Energy-sensitive currencies (like CAD, tied to oil) can react to a conflict even in a country with no direct connection, purely through the commodity channel.",
  },
];

export const commodityConcepts: ConceptEntry[] = [
  {
    id: "oil",
    term: "Oil",
    def: "One of the most-traded commodities in the world — its price is deeply tied to global growth expectations and specific producer/consumer economies.",
    accent: COMMODITY,
    how: "Countries that export large volumes of oil see their national income (and currency) rise and fall closely with the oil price; importers feel the opposite effect.",
    bullish: "Rising oil prices tend to support the currencies of major oil exporters, most notably CAD.",
    bearish: "Falling oil prices tend to weigh on major oil exporters' currencies while easing cost pressure for major importers.",
    mistake: "Assuming oil affects every currency the same way — the direction of the effect depends entirely on whether a country is a net exporter or importer.",
    tip: "CAD is the most closely-watched oil-correlated G10 currency — many traders track crude oil charts specifically for USD/CAD context.",
  },
  {
    id: "gold",
    term: "Gold",
    def: "A traditional safe-haven and store-of-value asset that tends to attract capital during uncertainty, inflation fears, or currency weakness.",
    accent: COMMODITY,
    how: "Gold doesn't pay any yield, so it competes directly with interest-bearing assets — it tends to do best when real interest rates are low and fear is high.",
    bullish: "Rising geopolitical risk, falling real interest rates, or inflation fears tend to push gold prices higher.",
    bearish: "Rising real interest rates and strong risk-on sentiment tend to pull capital away from gold and into yield-bearing assets.",
    mistake: "Treating gold as a simple 'risk-off' asset in every scenario — it can also fall during acute risk-off moments if investors need cash and sell everything, including gold.",
    tip: "Gold is priced in USD, so a stronger dollar is often (though not always) a headwind for gold, and vice versa — watch both together.",
  },
  {
    id: "iron-ore",
    term: "Iron Ore",
    def: "A key industrial commodity used mainly in steelmaking — a major export for resource-heavy economies like Australia.",
    accent: COMMODITY,
    how: "Iron ore demand is closely tied to global (especially Chinese) industrial and construction activity, making it a proxy for global manufacturing health.",
    bullish: "Strong Chinese industrial demand and rising iron ore prices tend to support AUD, given Australia's position as a major exporter.",
    bearish: "Weak Chinese demand or falling iron ore prices tend to weigh on AUD through reduced export income expectations.",
    mistake: "Watching AUD without any awareness of Chinese economic data — Chinese demand is often the real driver behind iron ore-linked AUD moves.",
    tip: "Chinese PMI and industrial production data can be leading indicators for AUD, even though they're not Australian releases themselves.",
  },
  {
    id: "agricultural-commodities",
    term: "Agricultural Commodities",
    def: "Dairy, meat, grains and other farm exports — a major share of national income for agriculture-heavy economies like New Zealand.",
    accent: COMMODITY,
    how: "Global demand and weather-driven supply shocks move agricultural prices, which directly affects export income for economies built around farm exports.",
    bullish: "Strong global demand or supply shortages pushing agricultural prices higher tends to support NZD.",
    bearish: "Weak global demand or a supply glut pushing agricultural prices lower tends to weigh on NZD.",
    mistake: "Overlooking seasonal and weather effects — agricultural supply shocks can be sudden and unrelated to broader macro trends.",
    tip: "New Zealand's dairy auction results are a specific, recurring data point some NZD traders track directly for early signals.",
  },
];
