import type { ConceptEntry } from "./ConceptAccordion";

const STRUCTURE = "var(--cat-1)";
const EVENT = "var(--gold)";

export const structureConcepts: ConceptEntry[] = [
  {
    id: "uptrend",
    term: "Uptrend",
    def: "A repeating pattern of Higher Highs and Higher Lows — buyers consistently in control.",
    accent: STRUCTURE,
    how: "Each pullback finds buyers before the last low, then price pushes past the last high. As long as that rhythm holds, the trend is considered intact.",
    bullish: "EUR/USD prints HH, HL, HH, HL for three weeks straight — trend traders keep buying each HL.",
    bearish: "Not applicable directionally, but the uptrend ending IS the bearish signal: watch for the first break below an HL (a CHoCH).",
    mistake: "Assuming an uptrend is broken after just one big red candle — one candle isn't structure, a broken HL is.",
    tip: "Try the \"Bullish Structure\" tab in the chart above and hover HH / HL to see exactly what confirms an uptrend is still alive.",
  },
  {
    id: "downtrend",
    term: "Downtrend",
    def: "A repeating pattern of Lower Highs and Lower Lows — sellers consistently in control.",
    accent: STRUCTURE,
    how: "Each bounce fails below the last high, then price pushes past the last low. The mirror image of an uptrend.",
    bullish: "The downtrend ending IS the bullish signal: watch for the first break above an LH (a CHoCH).",
    bearish: "GBP/JPY prints LH, LL, LH, LL for two weeks — trend traders keep selling each LH.",
    mistake: "Trying to catch the exact bottom instead of waiting for structure to actually flip.",
    tip: "Switch to \"Bearish Structure\" above and hover LL / LH to see the pattern build in real time.",
  },
  {
    id: "sideways",
    term: "Sideways Market",
    def: "Price bounces between a fairly flat ceiling and floor with no clear HH/HL or LH/LL pattern forming.",
    accent: STRUCTURE,
    how: "Neither buyers nor sellers can push price decisively in one direction, so it oscillates inside a defined band instead.",
    bullish: "Buying near the range floor with a tight stop just below it, targeting the range ceiling.",
    bearish: "Selling near the range ceiling with a tight stop just above it, targeting the range floor.",
    mistake: "Applying trend-following strategies (buying breakouts, riding pullbacks) inside a market that has no trend yet.",
    tip: "Check the \"Ranging Market\" tab above — this is exactly the price behavior that precedes many breakouts.",
  },
  {
    id: "hh",
    term: "Higher High — HH",
    def: "A swing high that prints above the previous swing high. The building block of an uptrend.",
    accent: STRUCTURE,
    how: "Price rallies, pulls back, then rallies again past the prior peak. That new peak is the HH.",
    bullish: "Price breaks above last week's high and keeps climbing — confirms buyers are still in charge.",
    bearish: "A failed attempt at a new high (price stalls just below the old high) can be an early warning sign.",
    mistake: "Marking every little wiggle as an HH — use a consistent, meaningful swing size so structure stays clean.",
    tip: "An HH that also breaks the most recent swing high is exactly what a BOS is.",
  },
  {
    id: "hl",
    term: "Higher Low — HL",
    def: "A swing low that prints above the previous swing low, without breaking it. Confirms an uptrend is intact.",
    accent: STRUCTURE,
    how: "After a new HH, price pulls back but finds buyers before reaching the last swing low.",
    bullish: "Many trend traders use a fresh HL as their preferred zone to enter long, with a stop just beneath it.",
    bearish: "If price instead breaks below the prior low, the HL fails — that's the CHoCH warning sign.",
    mistake: "Buying every dip blindly instead of waiting for the dip to actually hold as an HL first.",
    tip: "The HL is also your structural invalidation level — if it breaks, your bullish thesis is wrong.",
  },
  {
    id: "lh",
    term: "Lower High — LH",
    def: "A swing high that prints below the previous swing high. The building block of a downtrend.",
    accent: STRUCTURE,
    how: "Price falls, bounces, then fails to reach the prior peak before rolling back over.",
    bullish: "A rally that finally breaks above the last LH is often the first sign of a real trend change.",
    bearish: "Sellers often look to enter on the LH itself, anticipating the next leg down.",
    mistake: "Confusing a strong bounce with a trend change — it's only an LH if it fails below the prior high.",
    tip: "Combine LH with volume or a candlestick rejection pattern for a higher-confidence sell zone.",
  },
  {
    id: "ll",
    term: "Lower Low — LL",
    def: "A swing low that prints below the previous swing low. Confirms a downtrend is intact.",
    accent: STRUCTURE,
    how: "After a fresh LH, price breaks down past the last swing low, extending the downtrend.",
    bullish: "If price instead holds above the prior low and rallies, the downtrend structure is in question.",
    bearish: "A new LL that also breaks the most recent swing low is exactly what a BOS is in a downtrend.",
    mistake: "Shorting a market purely because it \"feels weak\" without an actual LL confirming it.",
    tip: "Stack LH + LL together and you've confirmed the full downtrend definition, not just half of it.",
  },
  {
    id: "bos",
    term: "Break of Structure — BOS",
    def: "Price closes beyond the most recent swing high (uptrend) or swing low (downtrend) — confirms the existing trend is continuing.",
    accent: EVENT,
    how: "A BOS is really just the moment an HH or LL is confirmed by a candle close, not merely a wick poking through.",
    bullish: "Price closes decisively above the last swing high in an uptrend — continuation traders add to longs.",
    bearish: "Price closes decisively below the last swing low in a downtrend — continuation traders add to shorts.",
    mistake: "Treating a wick-only break as a BOS. Most frameworks require a candle close beyond the level.",
    tip: "BOS confirms a trend is continuing — it is not a reversal signal. CHoCH is the reversal signal.",
  },
  {
    id: "choch",
    term: "Change of Character — CHoCH",
    def: "Price breaks the most recent swing low in an uptrend (or high in a downtrend) for the first time — the earliest warning a trend may be reversing.",
    accent: EVENT,
    how: "It's the exact opposite break of a BOS: instead of extending the trend, price violates the level that was protecting it.",
    bullish: "In a downtrend, price finally closes above the last swing high — the first clue sellers are losing control.",
    bearish: "In an uptrend, price finally closes below the last swing low — the first clue buyers are losing control.",
    mistake: "Reversing an entire position on the first CHoCH — many traders wait for a Market Structure Shift (follow-through) to confirm it.",
    tip: "Hover \"CHoCH\" on the chart above in either tab — notice it's always the very last point, breaking the opposite-side level.",
  },
];

const PRICE_ACTION = "var(--cat-2)";

export const priceActionConcepts: ConceptEntry[] = [
  {
    id: "rejection",
    term: "Rejection",
    def: "A candle with a long wick showing price was pushed sharply back after testing a level — proof that side lost the fight there.",
    accent: PRICE_ACTION,
    how: "Price probes above resistance or below support, gets overwhelmed by the opposite side, and closes back away from the extreme, leaving a long wick behind.",
    bullish: "A long lower wick at a support zone, closing near the candle's high — buyers defended the level hard.",
    bearish: "A long upper wick at a resistance zone, closing near the candle's low — sellers defended the level hard.",
    mistake: "Reacting to the wick in real time before the candle actually closes — the rejection isn't confirmed until it does.",
    tip: "A rejection at a level you already had marked (support/resistance, order block) is far more meaningful than a random one.",
  },
  {
    id: "momentum",
    term: "Momentum",
    def: "The speed and strength behind a price move — steep, strong-bodied candles show high momentum; small, choppy candles show low momentum.",
    accent: PRICE_ACTION,
    how: "Compare candle size and the angle of the move over a few periods. Big bodies with small wicks moving fast = strong momentum in that direction.",
    bullish: "A string of large green candles with tiny wicks, each closing near its high — strong bullish momentum.",
    bearish: "A string of large red candles with tiny wicks, each closing near its low — strong bearish momentum.",
    mistake: "Fading (trading against) strong momentum too early, assuming it must reverse immediately just because it moved fast.",
    tip: "Momentum fading near a key level (smaller candles, longer wicks) often precedes a reversal — watch for that shift.",
  },
  {
    id: "impulse-move",
    term: "Impulse Move",
    def: "A strong, fast, mostly one-directional move — the \"drive\" phase of a trend, usually followed by a pullback.",
    accent: PRICE_ACTION,
    how: "Large, same-direction candles with minimal overlap or retracement in between. Often the move that causes a BOS.",
    bullish: "A sharp rally through several prior swing highs in a handful of candles, with barely any pullback.",
    bearish: "A sharp decline through several prior swing lows in a handful of candles, with barely any bounce.",
    mistake: "Chasing an impulse move after it has already extended far from the last swing point — you're buying/selling into exhaustion.",
    tip: "The safer entry is usually the pullback that follows an impulse move, not the impulse itself.",
  },
  {
    id: "pullback",
    term: "Pullback",
    def: "A temporary move against the main trend before it continues — the market's way of \"catching its breath.\"",
    accent: PRICE_ACTION,
    how: "After an impulse move, some traders take profit and others fade the move short-term, causing a small retracement before the larger trend resumes.",
    bullish: "In an uptrend, a brief dip into a prior HL zone before price resumes climbing.",
    bearish: "In a downtrend, a brief bounce into a prior LH zone before price resumes falling.",
    mistake: "Confusing a pullback with a full trend reversal and exiting a good position too early.",
    tip: "A pullback that breaks structure (turns into a CHoCH) has stopped being a pullback — reassess the trend.",
  },
  {
    id: "consolidation",
    term: "Consolidation",
    def: "A pause where price chops sideways in a tight range, digesting the prior move before its next decision.",
    accent: PRICE_ACTION,
    how: "Buying and selling pressure roughly balance out, compressing price into a narrower and narrower band over time.",
    bullish: "Consolidation after a strong uptrend, followed by a breakout to the upside continuing the trend.",
    bearish: "Consolidation after a strong downtrend, followed by a breakdown to the downside continuing the trend.",
    mistake: "Trading breakout strategies too early while the range is still compressing — false starts are common here.",
    tip: "The longer and tighter the consolidation, the more explosive the eventual breakout tends to be.",
  },
  {
    id: "breakout",
    term: "Breakout",
    def: "Price exits a defined range, level, or pattern with real conviction — usually a strong-bodied candle and above-average volume.",
    accent: PRICE_ACTION,
    how: "Buying or selling pressure finally overwhelms the level that was containing price, and it closes clearly beyond it.",
    bullish: "Price closes decisively above range resistance on a strong candle, opening the door to the next leg up.",
    bearish: "Price closes decisively below range support on a strong candle, opening the door to the next leg down.",
    mistake: "Entering on the first touch of the level instead of waiting for an actual close beyond it.",
    tip: "A breakout that later comes back to retest the broken level (and holds) is generally considered the higher-probability entry.",
  },
  {
    id: "fakeout",
    term: "Fakeout",
    def: "A breakout that quickly fails and snaps back inside the range — a false signal that traps traders who entered too early.",
    accent: PRICE_ACTION,
    how: "Price pokes beyond a level, often on lower conviction (small body, thin volume), then reverses hard back through it.",
    bullish: "Price fakes a breakdown below support, sweeps stop-losses, then reverses sharply upward — often a liquidity grab.",
    bearish: "Price fakes a breakout above resistance, sweeps stop-losses, then reverses sharply downward — often a liquidity grab.",
    mistake: "Entering on the initial breakout candle alone with no confirmation — this is exactly how fakeouts catch traders.",
    tip: "Waiting for a candle close beyond the level (not just a touch) filters out a large share of fakeouts.",
  },
];
