import type { ConceptEntry } from "./ConceptAccordion";

const SD = "var(--cat-7)";
const LQ = "var(--cat-3)";

export const supplyDemandConcepts: ConceptEntry[] = [
  {
    id: "supply-zone",
    term: "Supply Zone",
    def: "An area where a sharp, one-sided move down started — evidence that sellers overwhelmed buyers there in size.",
    accent: SD,
    how: "Marked around the last up-candle(s) right before a strong down move, on the idea that leftover sell orders still rest in that area.",
    bullish: "Not applicable directly — a supply zone is where a bullish move is expected to stall or reverse.",
    bearish: "Price rallies back up into a marked supply zone and gets rejected sharply lower, just like in the chart above.",
    mistake: "Marking the zone too wide — the tighter and more precise the zone, the more useful it is.",
    tip: "A supply zone that price hasn't returned to yet (a \"fresh\" zone) tends to react more reliably than one visited many times.",
  },
  {
    id: "demand-zone",
    term: "Demand Zone",
    def: "An area where a sharp, one-sided move up started — evidence that buyers overwhelmed sellers there in size.",
    accent: SD,
    how: "Marked around the last down-candle(s) right before a strong up move, on the idea that leftover buy orders still rest in that area.",
    bullish: "Price falls back down into a marked demand zone and reacts sharply higher, just like in the chart above.",
    bearish: "Not applicable directly — a demand zone is where a bearish move is expected to stall or reverse.",
    mistake: "Buying the very first touch of a demand zone with no other confirmation at all.",
    tip: "Combine a demand zone with a bullish candlestick pattern (like a hammer) forming right inside it for a stronger signal.",
  },
  {
    id: "fresh-zone",
    term: "Fresh Zone",
    def: "A supply or demand zone that price has not returned to since it formed — none of the original orders there have been used up yet.",
    accent: SD,
    how: "The fewer times a zone has been \"tapped,\" the more of its original resting orders are still believed to be sitting there, unfilled.",
    bullish: "A fresh demand zone on its first retest often produces a sharper, faster reaction than an older one.",
    bearish: "A fresh supply zone on its first retest often produces a sharper, faster rejection than an older one.",
    mistake: "Treating every zone as equally strong regardless of how many times it's already been revisited.",
    tip: "All else equal, prioritize fresh zones over tested ones when several are lining up on your chart.",
  },
  {
    id: "tested-zone",
    term: "Tested Zone",
    def: "A supply or demand zone that price has already returned to and reacted from at least once.",
    accent: SD,
    how: "Each retest uses up some of the original resting orders, so the zone generally gets weaker with every additional visit.",
    bullish: "A demand zone tested twice with shrinking bounces each time is a warning it may not hold a third time.",
    bearish: "A supply zone tested twice with shrinking rejections each time is a warning it may not hold a third time.",
    mistake: "Expecting a heavily tested zone to react exactly as strongly as it did the very first time.",
    tip: "Watch the size of the reaction on each retest — shrinking reactions usually mean the zone is close to breaking.",
  },
  {
    id: "zone-break",
    term: "Zone Break",
    def: "Price finally pushes straight through a supply or demand zone instead of reacting from it — the zone has been used up.",
    accent: SD,
    how: "Once the resting orders inside a zone are exhausted, there's nothing left to stop price from continuing through it.",
    bullish: "Price breaks cleanly through an old supply zone and keeps climbing, absorbing all the sell orders that were left.",
    bearish: "Price breaks cleanly through an old demand zone and keeps falling, absorbing all the buy orders that were left.",
    mistake: "Continuing to trade a zone as if it still has orders in it, long after it's already been broken through.",
    tip: "A broken zone is exactly where a Supply/Demand Flip candidate begins — watch what happens on the retest.",
  },
  {
    id: "supply-demand-flip",
    term: "Supply/Demand Flip",
    def: "Once a supply or demand zone breaks, it frequently flips roles — old supply becomes new demand, and old demand becomes new supply.",
    accent: SD,
    how: "The same orders that used to stop price at the zone get replaced by new opposite-side orders from traders who missed the breakout and enter on the retest.",
    bullish: "Price breaks above an old supply zone, pulls back to retest it, holds as new demand, and continues higher.",
    bearish: "Price breaks below an old demand zone, pulls back to retest it, holds as new supply, and continues lower.",
    mistake: "Assuming a broken zone automatically flips every time — sometimes price just powers straight through without a retest at all.",
    tip: "This is the zone-based cousin of the Support/Resistance Flip covered in the previous lesson — same idea, different tool.",
  },
];

export const liquidityConcepts: ConceptEntry[] = [
  {
    id: "liquidity",
    term: "Liquidity",
    def: "How easily an asset can be bought or sold without moving its price much. In price action, it also refers to pools of resting orders sitting at a price level.",
    accent: LQ,
    how: "Deep liquidity means lots of buyers and sellers ready to trade at any moment — and lots of stop-losses and pending orders clustered at obvious levels.",
    bullish: "Large buy orders can be absorbed near a major low without crashing the price, because deep liquidity is sitting there.",
    bearish: "Thin liquidity (low volume hours, exotic pairs) means even small orders can cause outsized, sharp price moves.",
    mistake: "Trading exotic, illiquid pairs the same way you'd trade a major pair — spreads and slippage behave very differently.",
    tip: "The London/New York overlap generally has the deepest liquidity of the trading day — read more on the Foundations page.",
  },
  {
    id: "bsl",
    term: "Buy-Side Liquidity — BSL",
    def: "Resting buy-stop orders sitting above old highs — placed by short-sellers protecting their positions, and breakout traders going long.",
    accent: LQ,
    how: "Every time price forms a high that isn't immediately broken, both groups leave orders sitting just above it, building up a pool of liquidity.",
    bullish: "Price is drawn up toward a BSL pool because large players need that liquidity to fill sell orders into.",
    bearish: "After BSL is swept, price commonly reverses down hard once those buy-stops are triggered and absorbed.",
    mistake: "Assuming every push into old highs is a genuine breakout instead of a possible liquidity grab.",
    tip: "Try the \"Buy-Side Liquidity Sweep\" tab above to see exactly how this plays out on a chart.",
  },
  {
    id: "ssl",
    term: "Sell-Side Liquidity — SSL",
    def: "Resting sell-stop orders sitting below old lows — placed by long traders protecting their positions, and breakdown traders going short.",
    accent: LQ,
    how: "Every time price forms a low that isn't immediately broken, both groups leave orders sitting just below it, building up a pool of liquidity.",
    bullish: "After SSL is swept, price commonly reverses up hard once those sell-stops are triggered and absorbed.",
    bearish: "Price is drawn down toward an SSL pool because large players need that liquidity to fill buy orders into.",
    mistake: "Panic-selling into a sharp move below an old low without considering it might be a sweep, not a real breakdown.",
    tip: "Try the \"Sell-Side Liquidity Sweep\" tab above to see exactly how this plays out on a chart.",
  },
  {
    id: "equal-highs",
    term: "Equal Highs",
    def: "Two or more swing highs sitting at roughly the same price — a strong visual sign of a Buy-Side Liquidity pool building up.",
    accent: LQ,
    how: "The more times price fails at almost exactly the same high, the more obvious (and larger) that resting liquidity pool becomes to everyone watching.",
    bullish: "A push through equal highs with strong follow-through confirms a genuine breakout rather than a sweep.",
    bearish: "A quick spike above equal highs that immediately reverses is a classic liquidity sweep setup.",
    mistake: "Buying a breakout above equal highs the instant it happens, before waiting to see if it holds.",
    tip: "Equal highs are one of the most reliable places to expect a liquidity sweep before a real reversal.",
  },
  {
    id: "equal-lows",
    term: "Equal Lows",
    def: "Two or more swing lows sitting at roughly the same price — a strong visual sign of a Sell-Side Liquidity pool building up.",
    accent: LQ,
    how: "The more times price fails at almost exactly the same low, the more obvious (and larger) that resting liquidity pool becomes to everyone watching.",
    bullish: "A quick spike below equal lows that immediately reverses is a classic liquidity sweep setup.",
    bearish: "A push through equal lows with strong follow-through confirms a genuine breakdown rather than a sweep.",
    mistake: "Shorting a breakdown below equal lows the instant it happens, before waiting to see if it holds.",
    tip: "Equal lows are one of the most reliable places to expect a liquidity sweep before a real reversal.",
  },
  {
    id: "liquidity-sweep",
    term: "Liquidity Sweep",
    def: "A brief spike beyond a liquidity pool (equal highs/lows) that triggers the resting orders there before price reverses.",
    accent: LQ,
    how: "Large players need that resting liquidity to fill their own big orders, so price is pushed just far enough to trigger it before reversing.",
    bullish: "A sweep below sell-side liquidity followed by a sharp reversal up is a bullish signal for many price-action traders.",
    bearish: "A sweep above buy-side liquidity followed by a sharp reversal down is a bearish signal for many price-action traders.",
    mistake: "Confusing a genuine breakout with a sweep — the key difference is whether price holds beyond the level or snaps back.",
    tip: "Wait for a candle close back inside the prior range after the spike — that's the confirmation a sweep just happened.",
  },
  {
    id: "liquidity-grab",
    term: "Liquidity Grab",
    def: "Another name for the same event as a liquidity sweep — price \"grabs\" the resting orders at a level before reversing.",
    accent: LQ,
    how: "Used interchangeably with \"liquidity sweep\" and \"stop hunt\" across most price-action and Smart Money frameworks.",
    bullish: "A liquidity grab below a key low, followed by a strong bullish candle back above it.",
    bearish: "A liquidity grab above a key high, followed by a strong bearish candle back below it.",
    mistake: "Getting stopped out during the grab itself instead of anticipating it and placing stops with more room.",
    tip: "If your stop-loss sits exactly on an obvious equal high/low, you may be sitting right in the liquidity pool.",
  },
  {
    id: "stop-hunt",
    term: "Stop Hunt",
    def: "The retail-facing name for the same idea — a move that appears specifically designed to trigger clustered stop-losses before reversing.",
    accent: LQ,
    how: "Whether or not it's deliberate, the effect is the same: a level with obviously clustered stops gets tapped just before the real move happens.",
    bullish: "A stop hunt below support that reverses back up sharply, leaving behind a long lower wick.",
    bearish: "A stop hunt above resistance that reverses back down sharply, leaving behind a long upper wick.",
    mistake: "Placing stop-losses at the exact obvious level (just past a swing high/low) where everyone else's stops already are.",
    tip: "Give stops a little extra room beyond the obvious level, or use a structural invalidation point instead of the nearest swing point.",
  },
];
