import type { ConceptEntry } from "./ConceptAccordion";

const ACCENT = "var(--gold)";

export const supportResistanceConcepts: ConceptEntry[] = [
  {
    id: "what-is-support",
    term: "What is Support?",
    def: "A price level where buying pressure has historically been strong enough to stop a decline and push price back up.",
    accent: ACCENT,
    how: "Every time price falls to this area, enough buyers step in (or short-sellers take profit) that demand overwhelms supply, and the decline pauses or reverses.",
    bullish: "Price falls to a marked support zone, prints a bullish rejection candle, and rallies away from it.",
    bearish: "Price falls through support without hesitation and keeps going — the level failed to hold.",
    mistake: "Treating support as one exact price instead of a zone — react to the area, not a single pixel-perfect number.",
    tip: "Try the chart above: hover \"Support\" on the Bearish tab to see exactly where buyers previously stepped in.",
  },
  {
    id: "how-support-works",
    term: "How Support Works",
    def: "Support forms because traders remember price reacting there before — orders cluster around it, creating real buying pressure the next time price returns.",
    accent: ACCENT,
    how: "Memory and order flow: stop-losses, pending buy orders, and psychological \"it bounced here last time\" behavior all concentrate right around the same price area.",
    bullish: "A support zone that's been tested and held twice attracts even more buy orders on the third touch.",
    bearish: "A support zone that keeps getting tested with less and less bounce each time is quietly weakening.",
    mistake: "Assuming support will hold forever just because it held once — every level eventually breaks.",
    tip: "The reaction speed matters: a sharp, fast bounce off support is more convincing than a slow, grinding one.",
  },
  {
    id: "strong-support",
    term: "Strong Support",
    def: "A level that has been tested multiple times with clear, decisive rejections — and hasn't been broken.",
    accent: ACCENT,
    how: "Strength comes from repetition (multiple touches), the size of the reaction each time, and confluence with other levels (round numbers, prior structure, a trendline).",
    bullish: "A round-number level like 1.1000 that has bounced three separate times over several weeks.",
    bearish: "Even strong support eventually fails once enough sellers accumulate — no level is unbreakable forever.",
    mistake: "Overestimating strength from only one or two touches — three or more clean reactions is a better bar.",
    tip: "Stack confluence: support + a round number + a prior swing low together is stronger than any one alone.",
  },
  {
    id: "weak-support",
    term: "Weak Support",
    def: "A level that's only been touched once, reacted weakly, or is showing smaller and smaller bounces on each retest.",
    accent: ACCENT,
    how: "Fewer resting orders and less trader \"memory\" back it, so it takes far less selling pressure to break through.",
    bullish: "Occasionally still bounces once — but don't expect the same reliability as a well-tested level.",
    bearish: "Breaks on the first real selling pressure it faces, often without much of a fight.",
    mistake: "Placing the same size trade on weak support as you would on strong, well-confirmed support.",
    tip: "Size down (or skip) trades built around a level that hasn't proven itself with at least two clean reactions.",
  },
  {
    id: "what-is-resistance",
    term: "What is Resistance?",
    def: "A price level where selling pressure has historically been strong enough to stop a rally and push price back down.",
    accent: ACCENT,
    how: "The mirror image of support: every time price rallies into this area, sellers (or long-holders taking profit) overwhelm demand and the advance stalls.",
    bullish: "Price finally closes above resistance on strong volume, and buyers take control past the old ceiling.",
    bearish: "Price rallies into resistance, prints a bearish rejection candle, and reverses back down.",
    mistake: "Buying right into a resistance zone expecting a breakout without waiting for actual confirmation.",
    tip: "Hover \"Resistance\" on the Bullish tab above to see exactly where sellers previously took control.",
  },
  {
    id: "strong-resistance",
    term: "Strong Resistance",
    def: "A ceiling that's been tested multiple times with clear rejections — the sell-side mirror of strong support.",
    accent: ACCENT,
    how: "Same drivers as strong support: repeated touches, sharp reactions, and confluence with other technical levels.",
    bullish: "A breakout above genuinely strong resistance is a much bigger structural event than clearing a weak one.",
    bearish: "Strong resistance is where many traders look to fade rallies and enter short.",
    mistake: "Assuming resistance is automatically bearish forever — once it truly breaks, it often flips into support.",
    tip: "The more times a level has capped price, the more significant a genuine breakout above it becomes.",
  },
  {
    id: "weak-resistance",
    term: "Weak Resistance",
    def: "A ceiling that's only been touched once or is showing diminishing rejections on each retest.",
    accent: ACCENT,
    how: "Not enough resting sell orders have built up around it yet, so it takes relatively little buying pressure to clear it.",
    bullish: "Often the easiest resistance to break through cleanly, since few sellers are truly defending it.",
    bearish: "Can still produce a quick fade, but don't expect the reliability of a well-tested ceiling.",
    mistake: "Building a full conviction short around a resistance level that has barely been tested.",
    tip: "Weak resistance is where breakouts most often succeed — it just doesn't have much defending it yet.",
  },
  {
    id: "key-levels",
    term: "Key Levels",
    def: "The handful of support/resistance zones on a chart that matter most — usually major swing highs/lows or heavily-retested areas.",
    accent: ACCENT,
    how: "Traders mark the levels where price has reacted most sharply and most often, ignoring the dozens of minor wiggles in between.",
    bullish: "Price approaching a major key level from below often sees increased volatility and volume.",
    bearish: "Price approaching a major key level from above behaves the same way — expect a reaction, in either direction.",
    mistake: "Marking too many levels on a chart until every single one looks \"key\" — that defeats the purpose.",
    tip: "Fewer, higher-quality levels beat a chart cluttered with lines. Mark only where price reacted clearly.",
  },
  {
    id: "psychological-levels",
    term: "Psychological Levels",
    def: "Round numbers (1.1000, 1.2000, 150.00) that act as support/resistance simply because traders collectively watch and react to them.",
    accent: ACCENT,
    how: "Large numbers of stop-losses, take-profits, and pending orders naturally cluster around round figures, creating real supply/demand there even without a technical reason.",
    bullish: "GBP/USD approaching 1.3000 from below often slows down as sellers anticipate the round number.",
    bearish: "USD/JPY approaching 150.00 from above often sees the same hesitation from buyers.",
    mistake: "Ignoring round numbers entirely just because they aren't a \"real\" technical level — they still move price.",
    tip: "A round number that lines up with an existing swing high/low is usually a stronger level than either alone.",
  },
  {
    id: "trendline",
    term: "Trendline",
    def: "A diagonal line connecting a series of swing highs or swing lows — support and resistance that moves with the trend instead of sitting flat.",
    accent: ACCENT,
    how: "Connect two or more swing lows (in an uptrend) or swing highs (in a downtrend) with a straight line. Each time price returns to that line and reacts, it adds another point of confirmation — the more touches, the more traders watch it.",
    bullish: "In an uptrend, price repeatedly dips into a rising trendline connecting its swing lows, then bounces away from it each time.",
    bearish: "In a downtrend, price repeatedly rallies into a falling trendline connecting its swing highs, then gets rejected each time.",
    mistake: "Forcing a trendline through price using only two points, or steepening the angle to make it \"fit\" — a valid trendline should touch price naturally, not be redrawn to justify a bias.",
    tip: "A trendline break is read the same way as a horizontal support/resistance break: wait for a candle to close beyond it, not just wick through, before treating the trend as compromised.",
  },
  {
    id: "sr-flip",
    term: "Support/Resistance Flip",
    def: "Once a support or resistance level is broken with conviction, it frequently flips roles — old resistance becomes new support, and vice versa.",
    accent: ACCENT,
    how: "The traders who missed the breakout use the retest of the old level as their entry, which is exactly what creates the new reaction there.",
    bullish: "Price breaks above resistance, pulls back to retest it, holds, and continues higher — the flip confirmed.",
    bearish: "Price breaks below support, pulls back to retest it, gets rejected, and continues lower — the flip confirmed.",
    mistake: "Assuming every breakout will retest before continuing — sometimes price just keeps going without looking back.",
    tip: "This is exactly what the interactive chart above is showing — switch tabs and watch the flip happen.",
  },
  {
    id: "breakout",
    term: "Breakout",
    def: "Price closes decisively beyond a support or resistance level, signaling the level has failed to hold.",
    accent: ACCENT,
    how: "Buying or selling pressure finally overwhelms the orders defending the level, and a strong-bodied candle closes clearly on the other side.",
    bullish: "A strong candle closes above resistance with good momentum behind it.",
    bearish: "A strong candle closes below support with good momentum behind it.",
    mistake: "Entering the instant price touches the level instead of waiting for an actual close beyond it.",
    tip: "Combine a breakout with rising volume or momentum for a much higher-confidence signal.",
  },
  {
    id: "retest",
    term: "Retest",
    def: "After a breakout, price often returns to the broken level before continuing — a second chance to enter in the new direction.",
    accent: ACCENT,
    how: "Traders who missed the initial move place orders at the old level, and the level's new role (support or resistance) gets confirmed by that reaction.",
    bullish: "Price breaks resistance, dips back to retest it as support, holds, and resumes climbing.",
    bearish: "Price breaks support, bounces back to retest it as resistance, gets rejected, and resumes falling.",
    mistake: "Waiting so long for a retest that never comes that you miss the entire move.",
    tip: "A retest that holds with a clean rejection candle is generally considered the safer, higher-probability entry.",
  },
  {
    id: "fake-breakout",
    term: "Fake Breakout",
    def: "Price briefly breaks a level, triggers stop-losses and breakout entries, then reverses hard back inside — trapping traders on the wrong side.",
    accent: ACCENT,
    how: "Often driven by a burst of low-conviction volume (a liquidity sweep) rather than genuine supply/demand imbalance, so the move can't sustain itself.",
    bullish: "Price fakes a breakdown below support, sweeps stops, then reverses sharply upward.",
    bearish: "Price fakes a breakout above resistance, sweeps stops, then reverses sharply downward.",
    mistake: "Entering on the breakout candle itself with no confirmation — exactly how fake breakouts catch people.",
    tip: "Waiting for a candle close beyond the level (not just a wick) filters out a large share of fake breakouts.",
  },
];
