import type { ConceptEntry } from "@/components/technical-analysis/ConceptAccordion";

const ADV = "var(--cat-7)";

export const advancedConcepts: ConceptEntry[] = [
  {
    id: "volatility",
    term: "Volatility",
    def: "How large and fast a market's price moves are over a given period — high volatility means bigger, faster swings; low volatility means smaller, slower ones.",
    accent: ADV,
    how: "Volatility rises around major news events, session opens, and periods of uncertainty, and typically compresses during quiet, low-liquidity periods.",
    bullish: "Rising volatility ahead of a major data release can widen potential targets, but it also widens the range stops need to sit outside of.",
    bearish: "Falling volatility during a tight consolidation often precedes an eventual breakout — the market rarely stays this quiet indefinitely.",
    mistake: "Using the same stop-loss distance in all conditions — a stop sized for a quiet market is often too tight during a high-volatility news event.",
    tip: "Tools like the Average True Range (ATR) measure volatility directly, and many traders size stops as a multiple of ATR rather than a fixed pip count.",
  },
  {
    id: "correlation",
    term: "Correlation",
    def: "How closely two markets move in relation to each other, ranging from -1 (perfectly opposite) to +1 (perfectly together).",
    accent: ADV,
    how: "Pairs sharing a currency (like EUR/USD and GBP/USD, both quoted in USD) often move together; pairs on opposite sides of the same currency often move inversely.",
    bullish: "Recognizing that EUR/USD and USD/CHF are typically strongly negatively correlated helps avoid unknowingly doubling up on the same underlying USD bet.",
    bearish: "Taking multiple 'different' trades that are all actually highly correlated multiplies risk without the trader realizing their true total exposure.",
    mistake: "Treating five open positions as five independent risks, when several of them are really the same trade wearing different tickers.",
    tip: "Before adding a new position, check whether it's correlated with trades you already have open — true diversification requires low or negative correlation.",
  },
  {
    id: "advanced-risk-management",
    term: "Advanced Risk Management",
    def: "Managing risk across an entire portfolio of open positions, not just each trade in isolation.",
    accent: ADV,
    how: "This includes accounting for correlation between open trades, total exposure as a percentage of the account, and how a single major news event could affect several positions simultaneously.",
    bullish: "Capping total portfolio risk (not just per-trade risk) protects against the scenario where several correlated trades all lose at once.",
    bearish: "A trader risking 1% on each of five highly correlated trades may believe they're risking 5% total, when a single correlated move could realistically cost far more.",
    mistake: "Applying per-trade risk rules perfectly while ignoring how those trades interact with each other as a group.",
    tip: "Periodically review all open positions together and ask: if the worst plausible single event happened right now, what's the realistic combined loss?",
  },
  {
    id: "strategy-development",
    term: "Strategy Development",
    def: "The process of turning a trading idea into a fully defined, testable set of rules — entries, exits, position sizing, and the market conditions it's meant for.",
    accent: ADV,
    how: "A real strategy specifies exact, repeatable conditions (not vague feelings) for every decision, so it can be tested, reviewed, and followed consistently.",
    bullish: "A clearly defined strategy can be journaled, reviewed, and improved over time because every trade can be checked against the same fixed rules.",
    bearish: "A vague approach ('I buy dips in an uptrend') can't be meaningfully tested or improved, since 'a dip' means something different every time.",
    mistake: "Changing the rules of a strategy mid-stream based on recent results, rather than testing a new version separately before adopting it.",
    tip: "Write your strategy rules down in enough detail that someone else could follow them — if you can't do that, the rules aren't specific enough yet.",
  },
  {
    id: "backtesting",
    term: "Backtesting",
    def: "Testing a trading strategy's rules against historical price data to see how it would have performed in the past.",
    accent: ADV,
    how: "By applying a strategy's exact entry and exit rules to past charts, a trader can get a rough sense of its historical win rate, average risk:reward, and drawdown before ever risking live capital.",
    bullish: "A strategy that shows a reasonable win rate and manageable drawdown across several years and market conditions has at least survived more scrutiny than an untested idea.",
    bearish: "A strategy that only works on a handpicked, favorable stretch of history is unlikely to hold up once traded on new, unseen data.",
    mistake: "Curve-fitting — adjusting rules repeatedly until they perfectly match past data — which tends to break down immediately in live, forward conditions.",
    tip: "Test on more data than you fit rules to, and treat a positive backtest as a reason to move to a demo account next, not as a reason to trade real money immediately.",
  },
  {
    id: "performance-metrics",
    term: "Performance Metrics",
    def: "The specific numbers used to judge whether a trading strategy is actually working — beyond just 'am I up or down right now.'",
    accent: ADV,
    how: "Metrics like win rate, average risk:reward, maximum drawdown, and profit factor (gross profit ÷ gross loss) together give a far more complete picture than account balance alone.",
    bullish: "A strategy with a modest 45% win rate but a 1:2.5 average risk:reward can be solidly profitable — win rate alone would make it look weak.",
    bearish: "A strategy with an 80% win rate but occasional huge losses can still be a net loser — a high win rate alone doesn't guarantee profitability.",
    mistake: "Judging a strategy from a small number of trades — meaningful metrics typically need a much larger sample before they're trustworthy.",
    tip: "Track win rate, average risk:reward, and maximum drawdown together in your trading journal — no single number tells the whole story on its own.",
  },
];
