import type { Strategy } from "./StrategyAccordion";

export const strategies: Strategy[] = [
  {
    id: "scalping",
    name: "Scalping",
    def: "Taking many very short trades, each targeting a small number of pips, often holding positions for seconds to a few minutes.",
    accent: "var(--red)",
    how: "Scalpers rely on high trade frequency and tight spreads rather than large individual moves, closing positions quickly whether the trade goes for or against them.",
    example: "Entering EUR/USD for a 5-pip target with a 5-pip stop during a liquid session, repeated many times through the day.",
    conditions: "Needs tight spreads, low commission, fast execution, and high liquidity — typically the London and New York session overlaps.",
    advantages: "Many opportunities per day, and each individual trade is exposed to the market for only a short time.",
    limitations: "Extremely sensitive to spread and commission costs, which can quietly erode an otherwise-working edge; also demands intense, sustained focus.",
    risks: "High trade frequency means execution quality and costs matter enormously — a strategy that looks profitable on paper can lose money once real spreads and slippage are included.",
  },
  {
    id: "day-trading",
    name: "Day Trading",
    def: "Opening and closing all positions within the same trading day, never holding a trade overnight.",
    accent: "var(--cat-2)",
    how: "Day traders look for moves that play out over minutes to hours, using intraday chart structure, session behavior, and news events, then flatten all positions before the day ends.",
    example: "Trading a morning breakout on GBP/USD after a high-impact news release, closing the position before the session ends regardless of outcome.",
    conditions: "Works best in markets with enough intraday volatility and volume to produce tradable moves within a single session.",
    advantages: "No overnight swap/rollover exposure, and no risk from news or gaps happening while you're away from the screen.",
    limitations: "Requires being available and focused during active trading hours, which isn't practical for everyone's schedule.",
    risks: "Forcing a trade to fit within the session (or exiting purely because the day is ending) can override otherwise sound trade management.",
  },
  {
    id: "swing-trading",
    name: "Swing Trading",
    def: "Holding trades for several days to a few weeks, aiming to capture a larger 'swing' in price than an intraday trade would.",
    accent: "var(--mint)",
    how: "Swing traders use higher timeframes (like the 4-hour or daily chart) to identify a trend or reversal, entering with a wider stop and a proportionally larger target.",
    example: "Buying a pullback to a daily support zone in an uptrend, targeting the prior swing high over the following one to two weeks.",
    conditions: "Suits markets showing clear multi-day trends or ranges, and traders who can't watch charts constantly during the day.",
    advantages: "Requires far less screen time than scalping or day trading, and gives a trade room to develop without needing perfect intraday timing.",
    risks: "Positions are exposed to overnight and weekend gaps, plus swap/rollover costs for however long the trade stays open.",
    limitations: "Fewer trade opportunities than shorter-term styles, and the wider stops mean each loss (in price terms) is larger, even at the same account risk percentage.",
  },
  {
    id: "position-trading",
    name: "Position Trading",
    def: "A longer-term style holding trades for weeks to months, based primarily on major trends and underlying fundamentals.",
    accent: "var(--cat-1)",
    how: "Position traders combine higher-timeframe technical structure with fundamental context (interest rate cycles, economic trends) to hold a directional view over an extended period.",
    example: "Staying long a currency through a multi-month interest rate hiking cycle, holding through the normal short-term pullbacks along the way.",
    conditions: "Best suited to markets with a clear macro-driven trend, and traders comfortable holding through significant short-term volatility.",
    advantages: "Very low screen-time requirement day-to-day, and it aligns naturally with fundamental analysis rather than fighting against it.",
    limitations: "Ties up capital and margin for extended periods, and requires patience through drawdowns that can look alarming on a shorter timeframe.",
    risks: "A long holding period means more exposure to swap costs and to major unexpected events (elections, policy surprises) that can move price sharply against the position.",
  },
  {
    id: "trend-following",
    name: "Trend Following",
    def: "Entering in the direction of an already-established trend, on the assumption that a trend in motion tends to continue.",
    accent: "var(--cat-3)",
    how: "Traders identify a trend using structure (higher highs/higher lows) or tools like moving averages, then look for entries in that direction on pullbacks or continuation signals.",
    example: "Buying each higher low in a confirmed uptrend on the 4-hour chart, adding in the direction of the trend rather than against it.",
    conditions: "Needs a market that's actually trending — this approach tends to underperform in flat, choppy, range-bound conditions.",
    advantages: "Can capture large moves by staying in a trend for an extended period rather than exiting at the first small target.",
    limitations: "Tends to give back some profit at the actual trend reversal, since trend-followers are rarely first to exit at the exact top or bottom.",
    risks: "A high number of small losses can occur while waiting for the occasional large trending move — the strategy depends on those big wins covering the smaller losses.",
  },
  {
    id: "breakout-trading",
    name: "Breakout Trading",
    def: "Entering as price moves decisively beyond a defined level — like a range, triangle, or key support/resistance zone.",
    accent: "var(--gold)",
    how: "Traders identify a level where price has been contained, then enter once price closes convincingly beyond it, expecting the breakout to continue.",
    example: "Buying as price closes above a multi-week resistance level following a period of tight consolidation.",
    conditions: "Works best after genuine consolidation with building pressure — a random level with no real structure behind it is a much weaker signal.",
    advantages: "Can catch the very start of a new, strong directional move, often with an attractive risk:reward if the stop stays tight behind the broken level.",
    limitations: "Many apparent breakouts fail and reverse (a 'fakeout'), especially without confirmation like a strong close or above-average momentum.",
    risks: "Entering right at the breakout means the stop is often tight relative to normal volatility, so a brief false move can trigger it before the real move develops.",
  },
  {
    id: "pullback-trading",
    name: "Pullback Trading",
    def: "Entering during a temporary retracement against the main trend, rather than at the initial breakout or trend start.",
    accent: "var(--cat-4)",
    how: "Traders wait for an established trend to pause and pull back to a support/resistance zone, a moving average, or a Fibonacci level, entering as the pullback shows signs of ending.",
    example: "Buying a retracement into the 61.8% Fibonacci zone during an uptrend, once a bullish candlestick signal confirms buyers stepping back in.",
    conditions: "Requires an already-clear trend to pull back within — this doesn't apply in a genuinely range-bound or directionless market.",
    advantages: "Often provides a better entry price and tighter stop-loss placement than chasing the trend at its extension.",
    limitations: "A pullback can turn into a full trend reversal instead of resuming — distinguishing a healthy pullback from an actual reversal isn't always obvious in real time.",
    risks: "Entering too early in a still-developing pullback risks catching a falling market before it's actually found support.",
  },
  {
    id: "range-trading",
    name: "Range Trading",
    def: "Buying near the bottom and selling near the top of a well-defined horizontal range, rather than trading a trend.",
    accent: "var(--cyan)",
    how: "Traders identify a market bouncing between a fairly consistent floor (support) and ceiling (resistance), buying near the floor and selling near the ceiling until the range breaks.",
    example: "Selling near the top of a multi-week range on USD/CHF and buying back near the bottom, repeating as long as the range holds.",
    conditions: "Only suits genuinely range-bound, low-trend conditions — this approach performs poorly the moment the market starts trending.",
    advantages: "Offers clearly defined entry and exit zones, and the range boundaries double as natural stop-loss references.",
    limitations: "Ranges eventually break, and a range trader caught still buying the 'floor' as it finally gives way can take a larger-than-expected loss.",
    risks: "Confirmation bias toward 'the range will hold' can delay recognizing a genuine breakout, turning a small planned loss into a larger one.",
  },
  {
    id: "momentum-trading",
    name: "Momentum Trading",
    def: "Entering in the direction of a strong, fast-moving price surge, on the view that strong momentum tends to continue a while longer.",
    accent: "var(--cat-8)",
    how: "Traders look for sharp, high-volume moves — often confirmed with momentum indicators like RSI or MACD — and enter in the direction of the surge rather than waiting for a pullback.",
    example: "Entering long after a sharp upside move on strong volume and a rising MACD histogram, riding the continuation for as long as momentum holds.",
    conditions: "Best suited to volatile conditions with a clear catalyst (news, a data surprise) driving a genuine surge in one direction.",
    advantages: "Can capture fast, substantial moves in a short amount of time when momentum is genuinely strong.",
    limitations: "Momentum can fade very quickly, and entries are often made after a large part of the move has already happened.",
    risks: "Chasing a move that's already extended risks buying near a short-term exhaustion point, right before a sharp pullback.",
  },
];
