export type CountryTimeZone = {
  country: string;
  tz: string;
};

export const COUNTRY_TIMEZONES: CountryTimeZone[] = [
  { country: "Afghanistan", tz: "Asia/Kabul" },
  { country: "Argentina", tz: "America/Argentina/Buenos_Aires" },
  { country: "Australia (Sydney)", tz: "Australia/Sydney" },
  { country: "Australia (Perth)", tz: "Australia/Perth" },
  { country: "Austria", tz: "Europe/Vienna" },
  { country: "Bangladesh", tz: "Asia/Dhaka" },
  { country: "Belgium", tz: "Europe/Brussels" },
  { country: "Brazil", tz: "America/Sao_Paulo" },
  { country: "Canada (Toronto)", tz: "America/Toronto" },
  { country: "Canada (Vancouver)", tz: "America/Vancouver" },
  { country: "Chile", tz: "America/Santiago" },
  { country: "China", tz: "Asia/Shanghai" },
  { country: "Colombia", tz: "America/Bogota" },
  { country: "Denmark", tz: "Europe/Copenhagen" },
  { country: "Egypt", tz: "Africa/Cairo" },
  { country: "Finland", tz: "Europe/Helsinki" },
  { country: "France", tz: "Europe/Paris" },
  { country: "Germany", tz: "Europe/Berlin" },
  { country: "Greece", tz: "Europe/Athens" },
  { country: "Hong Kong", tz: "Asia/Hong_Kong" },
  { country: "India", tz: "Asia/Kolkata" },
  { country: "Indonesia", tz: "Asia/Jakarta" },
  { country: "Iran", tz: "Asia/Tehran" },
  { country: "Iraq", tz: "Asia/Baghdad" },
  { country: "Ireland", tz: "Europe/Dublin" },
  { country: "Israel", tz: "Asia/Jerusalem" },
  { country: "Italy", tz: "Europe/Rome" },
  { country: "Japan", tz: "Asia/Tokyo" },
  { country: "Jordan", tz: "Asia/Amman" },
  { country: "Kenya", tz: "Africa/Nairobi" },
  { country: "Kuwait", tz: "Asia/Kuwait" },
  { country: "Malaysia", tz: "Asia/Kuala_Lumpur" },
  { country: "Mexico", tz: "America/Mexico_City" },
  { country: "Morocco", tz: "Africa/Casablanca" },
  { country: "Nepal", tz: "Asia/Kathmandu" },
  { country: "Netherlands", tz: "Europe/Amsterdam" },
  { country: "New Zealand", tz: "Pacific/Auckland" },
  { country: "Nigeria", tz: "Africa/Lagos" },
  { country: "Norway", tz: "Europe/Oslo" },
  { country: "Oman", tz: "Asia/Muscat" },
  { country: "Pakistan", tz: "Asia/Karachi" },
  { country: "Philippines", tz: "Asia/Manila" },
  { country: "Poland", tz: "Europe/Warsaw" },
  { country: "Portugal", tz: "Europe/Lisbon" },
  { country: "Qatar", tz: "Asia/Qatar" },
  { country: "Romania", tz: "Europe/Bucharest" },
  { country: "Russia (Moscow)", tz: "Europe/Moscow" },
  { country: "Saudi Arabia", tz: "Asia/Riyadh" },
  { country: "Singapore", tz: "Asia/Singapore" },
  { country: "South Africa", tz: "Africa/Johannesburg" },
  { country: "South Korea", tz: "Asia/Seoul" },
  { country: "Spain", tz: "Europe/Madrid" },
  { country: "Sri Lanka", tz: "Asia/Colombo" },
  { country: "Sweden", tz: "Europe/Stockholm" },
  { country: "Switzerland", tz: "Europe/Zurich" },
  { country: "Taiwan", tz: "Asia/Taipei" },
  { country: "Thailand", tz: "Asia/Bangkok" },
  { country: "Turkey", tz: "Europe/Istanbul" },
  { country: "Ukraine", tz: "Europe/Kyiv" },
  { country: "United Arab Emirates", tz: "Asia/Dubai" },
  { country: "United Kingdom", tz: "Europe/London" },
  { country: "United States (New York)", tz: "America/New_York" },
  { country: "United States (Chicago)", tz: "America/Chicago" },
  { country: "United States (Denver)", tz: "America/Denver" },
  { country: "United States (Los Angeles)", tz: "America/Los_Angeles" },
  { country: "Vietnam", tz: "Asia/Ho_Chi_Minh" },
];
